package me.coley.puredds.rtps;

public enum LocatorKind {
	LOCATOR_INVALID,
	LOCATOR_KIND_INVALID,
	LOCATOR_KIND_RESERVED,
	LOCATOR_KIND_UDP_IPv4,
	LOCATOR_KIND_UDP_IPv6,
	LOCATOR_KIND_TCP_IPv4,
	LOCATOR_KIND_TCP_IPv6,
	LOCATOR_ADDRESS_INVALID,
	LOCATOR_PORT_INVALID
}
